class_name Operate extends RefCounted

enum {
	NONE,
	MOVE,
	PAN,
	ZOOM,
	PENCIL,
	BRUSH,
	ERASE,
	SHADING,
	CROP,
	COLORPICK,
	BUCKET,
	SELECT_RECTANGLE,
	SELECT_ELLIPSE,
	SELECT_POLYGON,
	SELECT_LASSO,
	SELECT_MAGIC,
	SHAPE_RECTANGLE,
	SHAPE_ELLIPSE,
	SHAPE_POLYGON,
	SHAPE_LINE,
}


const GROUP_SELECT = [SELECT_RECTANGLE, SELECT_ELLIPSE, 
					  SELECT_POLYGON, SELECT_LASSO, SELECT_MAGIC]
const GROUP_SHAPE = [SHAPE_RECTANGLE, SHAPE_ELLIPSE,
					 SHAPE_POLYGON, SHAPE_LINE]
